(global-set-key (kbd "<f2> i") '(lambda () (interactive) (insert "~/.emacs.d/init.el")))
(global-set-key (kbd "<f2> p") '(lambda () (interactive) (insert "~/programming/_projects/pdf-something")))
(global-set-key (kbd "<f2> e") '(lambda () (interactive) (insert "~/programming/macOS/easyLyceum")))
(global-set-key (kbd "<f2> y") '(lambda () (interactive) (insert "~/.emacs.d/snippets/")))
(global-set-key (kbd "<f2> t") '(lambda () (interactive) (insert "~/bioinformatics/thesis/R/TargetScanTools")))
(global-set-key (kbd "<f2> l") '(lambda () (interactive) (insert "~/bioinformatics/thesis/latex")))
(global-set-key (kbd "<f2> c") '(lambda () (interactive) (insert "~/bioinformatics/thesis/R/TargetScanTools")))
