;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	LaTeX-insert-left-brace
	LaTeX-math-sigma
	TeX-insert-backslash
	TeX-insert-dollar
	TeX-insert-sub-or-superscript
	beginning-of-visual-line
	comment-dwim
	end-of-visual-line
	forward-whitespace
	kill-visual-line
	repeat
	toggle-input-method
	))

(setq mc/cmds-to-run-once
      '(
	TeX-newline
	goto-line
	org-self-insert-command
	))
